import type { Metadata } from "next";
import { cn } from "@/lib/utils";
import { componentList } from "@/blocks/data";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <div>{children}</div>
//   );
// }


// Generate segments for [category]
export async function generateStaticParams() {
  const categories = Object.keys(componentList)
  console.log('got keys from component list:', categories)

  return categories.map(cat => ({
    category: cat,
  }))
}

export default function Layout({ params, children }: { params: { category: string }, children: React.ReactNode }) {
    return (
      <div className="p-4">
        {/* <pre>CATEGORY LAYOUT PARAMS: {JSON.stringify(params, null, 2)}</pre> */}
        {children}
      </div>
    );
}