import type { Metadata } from "next";
import { cn } from "@/lib/utils";
import { Panel } from "@/components/panel";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: any
}>) {
  return (
    <Panel>
      {children}
    </Panel>
  );
}
